CREATE TABLE `cheques` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CHEQUE_NO` varchar(20) DEFAULT NULL,
  `CHEQUE_NAME` varchar(40) DEFAULT NULL,
  `BRANCH` varchar(20) DEFAULT NULL,
  `CITY` varchar(20) DEFAULT NULL,
  `STATUS` varchar(20) DEFAULT NULL,
  `AMOUNT` int(11) DEFAULT NULL,
  `NAME` varchar(40) DEFAULT NULL,
  `BANK` varchar(20) DEFAULT NULL,
  `CHEQUE_DATE` varchar(20) DEFAULT NULL,
  `DEPOSITED_DATE` varchar(20) DEFAULT NULL,
  `COMMENTS` varchar(100) DEFAULT NULL,
  `PAYMENT_ID` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=474 DEFAULT CHARSET=latin1;

CREATE TABLE `daily_mail_list` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CLASS_TYPE` varchar(20) DEFAULT NULL,
  `MAIL_LIST` varchar(2500) DEFAULT NULL,
  `TIME` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;

CREATE TABLE `daily_report` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTENT` varchar(5000) DEFAULT NULL,
  `STATUS` tinyint(4) DEFAULT '0',
  `SEND_DATE` varchar(20) DEFAULT NULL,
  `MAIL_ID` varchar(2000) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `SUBJECT` varchar(200) DEFAULT NULL,
  `TIME` varchar(20) DEFAULT NULL,
  `TO_SEND` tinyint(4) DEFAULT '0',
  `DELETED` tinyint(4) DEFAULT '0',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=29 DEFAULT CHARSET=latin1;

CREATE TABLE `email_id` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `GROUP` varchar(50) DEFAULT NULL,
  `EMAIL_ID` varchar(2000) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `SEND_TIME` varchar(20) DEFAULT NULL,
  `CLASS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=latin1;

CREATE TABLE `expense` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) DEFAULT NULL,
  `DESCRIPTION` varchar(20) DEFAULT NULL,
  `MONTH` varchar(20) DEFAULT NULL,
  `AMOUNT` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=47 DEFAULT CHARSET=latin1;

CREATE TABLE `mail_info` (
  `CREATE_DATE` varchar(20) DEFAULT NULL,
  `MODIFIED_DATE` varchar(20) DEFAULT NULL,
  `MAIL_SENT` char(1) DEFAULT 'N',
  `SUBJECT` varchar(200) DEFAULT NULL,
  `BODY` varchar(1000) DEFAULT NULL,
  `MAILER_LIST` varchar(1000) DEFAULT NULL,
  `ATTACHMENT_PATH` varchar(200) DEFAULT NULL,
  `ATTACHMENT_FILE` varchar(50) DEFAULT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=latin1;

CREATE TABLE `payment_details` (
  `STUDENT_ID` int(11) DEFAULT NULL,
  `CLASS` varchar(20) DEFAULT NULL,
  `TERM` varchar(20) DEFAULT NULL,
  `STATUS` tinyint(1) DEFAULT '0',
  `TYPE` varchar(20) DEFAULT NULL,
  `PAID_DATE` varchar(20) DEFAULT NULL,
  `MONTH` varchar(20) DEFAULT NULL,
  `COMMENTS` varchar(900) DEFAULT NULL,
  `BOOK` int(11) DEFAULT NULL,
  `ACTIVITY` int(11) DEFAULT NULL,
  `TERM_FEES` int(11) DEFAULT NULL,
  `ADMISSION` int(11) DEFAULT NULL,
  `TRANSPORT` int(11) DEFAULT NULL,
  `DAYCARE` int(11) DEFAULT NULL,
  `ART` int(11) DEFAULT NULL,
  `DANCE` int(11) DEFAULT NULL,
  `SNACKS` int(11) DEFAULT NULL,
  `LUNCH` int(11) DEFAULT NULL,
  `BF` int(11) DEFAULT NULL,
  `ADHOC` int(11) DEFAULT NULL,
  `OTHERS` int(11) DEFAULT NULL,
  `TOTAL` int(11) DEFAULT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `UNIFORM` int(11) DEFAULT '0',
  `SENTMAIL` smallint(6) DEFAULT '0',
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3037 DEFAULT CHARSET=latin1;

CREATE TABLE `students` (
  `NAME` varchar(25) DEFAULT NULL,
  `CLASS` varchar(20) DEFAULT NULL,
  `EMAIL_1` varchar(80) DEFAULT NULL,
  `EMAIL_2` varchar(80) DEFAULT NULL,
  `ACTIVE` smallint(6) DEFAULT '0',
  `TELEPHONE_1` varchar(20) DEFAULT NULL,
  `TELEPHONE_2` varchar(20) DEFAULT NULL,
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `YEAR` int(11) DEFAULT NULL,
  `CREATED_DATE` datetime DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=701 DEFAULT CHARSET=latin1;

